name: ChenHuei Wordle
on:
  push:
    branches: ["main"]
jobs:
  build:
    environment:
      name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: npm install
        run: |
          npm ci
          npm run build
      - name: upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
  lighthouse:
    environment:
      name: Lighthouse
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://chenhuei.github.io/Wordle
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
  deploy:
    environment:
      name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
